// Generated by https://quicktype.io

export interface BranchResponse {
  encodedKey: string
  id: string
  creationDate: string
  lastModifiedDate: string
  name: string
  state: string
  phoneNumber: string
  emailAddress: string
}
