// Generated by https://quicktype.io

export interface InterestaccrualInterface {
  transactionId: string
  accountKey: string
  accountId: string
  branchKey?: string
  branchName?: string
  productKey: string
  productType: string
  productId: string
  bookingDate: string
  entryId: number
  parentEntryId: number
  entryType: string
  amount: number
  creationDate: string
  glAccountKey: string
  glAccountType: string
  glAccountName: string
  glAccountId: string
  foreignAmount: ForeignAmount
}

export interface ForeignAmount {}
