// Generated by https://quicktype.io

export interface JournalEntriesResponse {
  creationDate: string
  bookingDate: string
  amount: number
  glAccount: GlAccount
  type: string
  assignedBranchKey: string
}

export interface GlAccount {
  glCode: string
  currency: Currency
}

export interface Currency {
  //currencyCode: string;
  code: string
}
